# Site settings
title: 메모 블로그
header-img: img/background.png
email: shinhj7242@gmail.com
copyright_name: HEEJUN/memo Blog/programming study
description: "hello world!!"
baseurl:
url: "http://shj7242.github.io"
twitter_username: shinhj7242
github_username:  shj7242
facebook_username:  profile.php?id=100002266059179
email_username:  shinhj7242@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
des: 메모 / 기술 블로그


# Search settings
tipue_search:
  include:
    pages: false
    collections: []
  exclude:
    files: [search.html, index.html, tags.html]
    categories: []
    tags: []